//===- MXDialect.td - MX dialect -----------*- tablegen -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef MX_DIALECT
#define MX_DIALECT

include "mlir/IR/OpBase.td"

//===----------------------------------------------------------------------===//
// MX dialect definition.
//===----------------------------------------------------------------------===//

def MX_Dialect : Dialect {
    let name = "mx";
    let summary = "A mx out-of-tree MLIR dialect.";
    let description = [{
        This dialect is an example of an out-of-tree MLIR dialect designed to
        illustrate the basic setup required to develop MLIR-based tools without
        working inside of the LLVM source tree.
    }];
    let cppNamespace = "::mlir::mx";

    let useDefaultTypePrinterParser = 1;
    let extraClassDeclaration = [{
        void registerTypes();
    }];
}

//===----------------------------------------------------------------------===//
// Base mx operation definition.
//===----------------------------------------------------------------------===//

class MX_Op<string mnemonic, list<Trait> traits = []> :
        Op<MX_Dialect, mnemonic, traits>;

#endif // MX_DIALECT
